name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-basic:
    name: Test |${{ matrix.build_type }}| on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON -DBUILD_TESTS_SANITIZED=OFF

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        working-directory: build

        run: ctest --output-on-failure -C ${{ matrix.build_type }}

  test-sanitized:
    name: Sanitized Tests |${{ matrix.build_type }}| on ${{ matrix.os }}
    needs: test-basic
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=OFF -DBUILD_TESTS_SANITIZED=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        working-directory: build

        run: ctest --output-on-failure -C ${{ matrix.build_type }}

  all-possible-test:
    name: All Tests on |${{ matrix.build_type }}| on ${{ matrix.os }}
    needs: [test-basic, test-sanitized]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON -DBUILD_TESTS_SANITIZED=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        working-directory: build

        run: ctest --output-on-failure

  call-release:
    needs: [test-basic, test-sanitized, all-possible-test]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
