name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: test-binaries-${{ matrix.os }}
          path: build_debug/

      - name: Make binaries executable (Unix only)
        if: runner.os != 'Windows'
        run: chmod -R +x build_debug/

      - name: Run All Tests via CTest
        working-directory: build_debug
        run: ctest --output-on-failure -C Debug
